# Copyright 2020-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0

# cassandra values
cassandra:
  config:
    cluster_size: 1
    seed_size: 1

resources:
  enabled: false

config:
  spgwc:
    pfcp: true
    ueIpPool:
      ip: 172.250.0.0 # if we use RiaB, Makefile script will override this value with the value defined in Makefile script.
  upf:
    name: "oaisim"
    sriov:
      enabled: false
    hugepage:
      enabled: false
    cniPlugin: simpleovs
    ipam: static
    cfgFiles:
      upf.json:
        mode: af_packet
  mme:
    cfgFiles:
      config.json:
        mme:
          mcc:
            dig1: 2
            dig2: 0
            dig3: 8
          mnc:
            dig1: 0
            dig2: 1
            dig3: -1
          apnlist:
            internet: "spgwc"
  hss:
    bootstrap:
      users:
        - apn: "internet"
          key: "465b5ce8b199b49faa5f0a2ee238a6bc"
          opc: "d4416644f6154936193433dd20a0ace0"
          sqn: 96
          imsiStart: "208014567891201"
          msisdnStart: "1122334455"
          count: 10
      mmes:
        - id: 1
          mme_identity: mme.riab.svc.cluster.local
          mme_realm: riab.svc.cluster.local
          isdn: "19136246000"
          unreachability: 1
  oai-enb-cu:
    networks:
      f1:
        interface: eno1 # if we use RiaB, Makefile script will automatically apply appropriate interface name
        address: 10.128.100.100 #if we use RiaB, Makefile script will automatically apply appropriate IP address
      s1mme:
        interface: eno1 # if we use RiaB, Makefile script will automatically apply appropriate interface name
      s1u:
        interface: enb
  oai-enb-du:
    mode: nfapi #or local_L1 for USRP and BasicSim
    networks:
      f1:
        interface: eno1 #if we use RiaB, Makefile script will automatically apply appropriate IP address
        address: 10.128.100.100 #if we use RiaB, Makefile script will automatically apply appropriate IP address
      nfapi:
        interface: eno1 #if we use RiaB, Makefile script will automatically apply appropriate IP address
        address: 10.128.100.100 #if we use RiaB, Makefile script will automatically apply appropriate IP address
  oai-ue:
    networks:
      nfapi:
        interface: eno1 #if we use RiaB, Makefile script will automatically apply appropriate IP address
        address: 10.128.100.100 #if we use RiaB, Makefile script will automatically apply appropriate IP address
  onos-e2t:
    enabled: "yes"
    networks:
      e2:
        address: 127.0.0.1 # if we use RiaB, Makefile script will automatically apply appropriate interface name
        port: 36421

# for the development, we can use the custom images
# For ONOS-RIC
#onos-topo:
#  image:
#    pullPolicy: Always
#    repository: onosproject/onos-topo
#    tag: latest
#  logging:
#    loggers:
#      root:
#        level: info
#onos-config:
#  image:
#    pullPolicy: Always
#    repository: onosproject/onos-config
#    tag: latest
#  logging:
#    loggers:
#      root:
#        level: info
#onos-e2t:
#  image:
#    pullPolicy: Always
#    repository: onosproject/onos-e2t
#    tag: latest
#   servicemodels:
#   - name: e2sm_kpm
#     version: 1.0.0
#     image:
#       repository: onosproject/service-model-docker-e2sm_kpm-1.0.0
#       tag: v0.6.5
#       pullPolicy: IfNotPresent
#   - name: e2sm_ni
#     version: 1.0.0
#     image:
#       repository: onosproject/service-model-docker-e2sm_ni-1.0.0
#       tag: v0.6.5
#       pullPolicy: IfNotPresent
#  logging:
#    loggers:
#      root:
#        level: info
#onos-e2sub:
#  image:
#    pullPolicy: Always
#    repository: onosproject/onos-e2sub
#    tag: latest
#  logging:
#    loggers:
#      root:
#        level: info
#onos-sdran-cli:
#  image:
#    pullPolicy: Always
#    repository: onosproject/onos-sdran-cli
#    tag: latest
#  logging:
#    loggers:
#      root:
#        level: info
#onos-kpimon:
#  image:
#    pullPolicy: Always
#    repository: onosproject/onos-kpimon
#    tag: latest
#  logging:
#    loggers:
#      root:
#        level: info

# For OMEC & OAI
images:
  pullPolicy: IfNotPresent
  tags:
# For OMEC - Those images are stable image for RiaB
# latest Aether helm chart commit ID: 3d1e936e87b4ddae784a33f036f87899e9d00b95
#    init: docker.io/omecproject/pod-init:1.0.0
#    depCheck: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
    hssdb: docker.io/onosproject/riab-hssdb:v1.0.0
    hss: docker.io/onosproject/riab-hss:v1.0.0
    mme: docker.io/onosproject/riab-nucleus-mme:v1.0.0
    spgwc: docker.io/onosproject/riab-spgw:v1.0.0
    pcrf: docker.io/onosproject/riab-pcrf:v1.0.0
    pcrfdb: docker.io/onosproject/riab-pcrfdb:v1.0.0
    bess: docker.io/onosproject/riab-bess-upf:v1.0.0
    pfcpiface: docker.io/onosproject/riab-pfcpiface:v1.0.0
# For OAI
#     oaicucp: docker.io/onosproject/oai-enb-cu:latest
#     oaidu: docker.io/onosproject/oai-enb-du:latest
#     oaiue: docker.io/onosproject/oai-enb-ue:latest

# For SD-RAN Umbrella chart:
# ONOS-KPIMON xAPP is imported in the RiaB by default
import:
  onos-kpimon:
    enabled: true
# Other ONOS-RIC micro-services
#   onos-topo:
#     enabled: true
#   onos-e2t:
#     enabled: true
#   onos-e2sub:
#     enabled: true
#   onos-o1t:
#     enabled: false
#   onos-config:
#     enabled: true
#   onos-sdran-cli:
#     enabled: true
# ran-simulator chart is automatically imported when pushing ransim option
#   ran-simulator:
#     enabled: false
#   onos-gui:
#     enabled: false
#   nem-monitoring:
#     enabled: false
