# Copyright 2020-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0

# cassandra values
cassandra:
  config:
    cluster_size: 1
    seed_size: 1

resources:
  enabled: false

5g-control-plane:
  enable5G: false

5g-ran-sim:
  enable: false

omec-sub-provision:
  enable: false

omec-control-plane:
  enable4G: true
  config:
    coreDump:
      enabled: false
    hss:
      bootstrap:
        users:
          - apn: internet
            key: "465b5ce8b199b49faa5f0a2ee238a6bc"
            opc: "d4416644f6154936193433dd20a0ace0"
            sqn: 96
            imsiStart: "208014567891200"
            msisdnStart: "1122334455"
            mme_identity: mme.riab.svc.cluster.local
            mme_realm: riab.svc.cluster.local
            count: 10
        staticusers:
          - apn: internet
            key: "465b5ce8b199b49faa5f0a2ee238a6bc"
            opc: "d4416644f6154936193433dd20a0ace0"
            sqn: 96
            imsi: "208014567891300"
            msisdn: "1122334455"
            staticAddr: 0.0.0.0
            mme_identity: mme.riab.svc.cluster.local
            mme_realm: riab.svc.cluster.local
        mmes:
          - id: 1
            mme_identity: mme.riab.svc.cluster.local
            mme_realm: riab.svc.cluster.local
            isdn: "19136246000"
            unreachability: 1
    mme:
      cfgFiles:
        config.json:
          mme:
            apnlist:
              internet: "spgwc"
            plmnlist:
              plmn1: "mcc=315,mnc=010"
              plmn2: "mcc=208,mnc=01"
    spgwc:
      cfgFiles:
        cp.json:
          ip_pool_config:
            ueIpPool:
              ip: 172.250.0.0 # if we use RiaB, Makefile script will override this value with the value defined in MakefileVar.mk file.
            staticUeIpPool:
              ip: 172.249.0.0 # if we use RiaB, Makefile script will override this value with the value defined in MakefileVar.mk file.
        subscriber_mapping.json:
          subscriber-selection-rules:
            - priority: 5
              keys:
                serving-plmn:
                  mcc: 208
                  mnc: 10
                  tac: 1
                imsi-range:
                  from: 200000000000000
                  to: 299999999999999
              selected-apn-profile: apn-profile1
              selected-qos-profile: qos-profile1
              selected-access-profile:
                - access-all
              selected-user-plane-profile: user-plane1
            - priority: 10
              keys:
                match-all: true
              selected-apn-profile: apn-profile1
              selected-qos-profile: qos-profile1
              selected-access-profile:
                - access-all
              selected-user-plane-profile: user-plane1
          apn-profiles:
            apn-profile1:
              apn-name: internet
              usage: 1
              network: lbo
              gx_enabled: true
              dns_primary: 8.8.8.4
              dns_secondary: 8.8.8.8
              mtu: 1460
          user-plane-profiles:
            user-plane1:
              user-plane: upf
              global-address: true
              qos-tags:
                tag1: BW
              access-tags:
                tag1: ACC
          qos-profiles:
            mobile:
              qci: 9
              arp: 1
              apn-ambr:
                - 12345678
                - 12345678
          access-profiles:
            access-all:
              type: allow-all
            internet-only:
              type: internet-only
              filter: No_private_network
            intranet-only:
              type: intranet-only
              filter: only_private_network
            apps-only:
              type: specific-network
              filter: only_apps_network
            specific-app:
              type: specific-destination-only
              filter: allow-app-name
            excluding-app:
              type: excluding-this-app
              filter: exclude-app-name
omec-user-plane:
  resources:
    enabled: true
    bess:
      requests:
        cpu: 2
        memory: 2Gi
      limits:
        cpu: 2
        memory: 2Gi
    routectl:
      requests:
        cpu: 256m
        memory: 128Mi
      limits:
        cpu: 256m
        memory: 128Mi
    web:
      requests:
        cpu: 256m
        memory: 128Mi
      limits:
        cpu: 256m
        memory: 128Mi
    cpiface:
      requests:
        cpu: 256m
        memory: 128Mi
      limits:
        cpu: 256m
        memory: 128Mi
  enable: true
  config:
    upf:
      privileged: true
      enb:
        subnet: 192.168.251.0/24
      access:
        ipam: static
        cniPlugin: simpleovs
        gateway: 192.168.252.1
        ip: 192.168.252.3/24
      core:
        ipam: static
        cniPlugin: simpleovs
        gateway: 192.168.250.1
        ip: 192.168.250.3/24
      name: "oaisim"
      sriov:
        enabled: false
      hugepage:
        enabled: false
      cniPlugin: simpleovs
      ipam: static
      cfgFiles:
        upf.jsonc:
          mode: af_packet                # This mode implies no DPDK
          hwcksum: true
          log_level: "info"
          cpiface:
            dnn: "internet"
            hostname: "upf"
            enable_ue_ip_alloc: false
            ue_ip_pool: 172.250.0.0/16 # if we use RiaB, Makefile script will override this value with the value defined in MakefileVar.mk file.
          slice_rate_limit_config:       # Slice-level rate limiting (also controlled by ROC)
            # Uplink
            n6_bps: 10000000000          # 10Gbps
            n6_burst_bytes: 12500000     # 10ms * 10Gbps
            # Downlink
            n3_bps: 10000000000          # 10Gbps
            n3_burst_bytes: 12500000     # 10ms * 10Gbps

config:
  oai-enb-cu:
    networks:
      f1:
        interface: eno1 # if we use RiaB, Makefile script will automatically apply appropriate interface name
        address: 10.128.100.100 #if we use RiaB, Makefile script will automatically apply appropriate IP address
      s1mme:
        interface: eno1 # if we use RiaB, Makefile script will automatically apply appropriate interface name
      s1u:
        interface: enb
  oai-enb-du:
    mode: nfapi #or local_L1 for USRP and BasicSim
    networks:
      f1:
        interface: eno1 #if we use RiaB, Makefile script will automatically apply appropriate IP address
        address: 10.128.100.100 #if we use RiaB, Makefile script will automatically apply appropriate IP address
      nfapi:
        interface: eno1 #if we use RiaB, Makefile script will automatically apply appropriate IP address
        address: 10.128.100.100 #if we use RiaB, Makefile script will automatically apply appropriate IP address
  oai-ue:
    numDevices: 1 # support up to 3
    networks:
      nfapi:
        interface: eno1 #if we use RiaB, Makefile script will automatically apply appropriate IP address
        address: 10.128.100.100 #if we use RiaB, Makefile script will automatically apply appropriate IP address
  onos-e2t:
    enabled: "yes"
    networks:
      e2:
        address: 127.0.0.1 # if we use RiaB, Makefile script will automatically apply appropriate interface name
        port: 36421

# for the development, we can use the custom images
# For ONOS-RIC
# onos-topo:
#   image:
#     pullPolicy: IfNotPresent
#     repository: onosproject/onos-topo
#     tag: v0.7.3
#   logging:
#     loggers:
#       root:
#         level: info
# onos-config:
#   image:
#     pullPolicy: IfNotPresent
#     repository: onosproject/onos-config
#     tag: v0.7.18
#   logging:
#     loggers:
#       root:
#         level: info
onos-e2t:
  service:
    external:
      enabled: true
    e2:
     nodePort: 36421
#   image:
#     pullPolicy: IfNotPresent
#     repository: onosproject/onos-e2t
#     tag: v0.7.14
#   logging:
#     loggers:
#       root:
#         level: info
# onos-e2sub:
#   image:
#     pullPolicy: IfNotPresent
#     repository: onosproject/onos-e2sub
#     tag: v0.7.3
#   logging:
#     loggers:
#       root:
#         level: info
# onos-cli:
#   image:
#     pullPolicy: IfNotPresent
#     repository: onosproject/onos-cli
#     tag: v0.7.11
#   logging:
#     loggers:
#       root:
#         level: info
# ran-simulator:
#   image:
#     pullPolicy: IfNotPresent
#     repository: onosproject/ran-simulator
#     tag: v0.7.24
#   logging:
#     loggers:
#       root:
#         level: info
# onos-kpimon-v1:
#   image:
#     pullPolicy: IfNotPresent
#     repository: onosproject/onos-kpimon
#     tag: v0.1.7
#   logging:
#     loggers:
#       root:
#         level: info
# onos-kpimon-v2:
#   image:
#     pullPolicy: IfNotPresent
#     repository: onosproject/onos-kpimon
#     tag: v0.1.7
#   logging:
#     loggers:
#       root:
#         level: info
# onos-pci:
#   image:
#     pullPolicy: IfNotPresent
#     repository: onosproject/onos-pci
#     tag: v0.1.2
#   logging:
#     loggers:
#       root:
#         level: info
# fb-ah-xapp:
#   image:
#     repository: onosproject/fb-ah-xapp
#     tag: 0.0.1
#     pullPolicy: IfNotPresent
# fb-ah-gui:
#   image:
#     repository: onosproject/fb-ah-gui
#     tag: 0.0.1
#     pullPolicy: IfNotPresent
# ah-eson-test-server:
#   image:
#     repository: onosproject/ah-eson-test-server
#     tag: 0.0.1
#     pullPolicy: IfNotPresent

# For OMEC & OAI
images:
  pullPolicy: IfNotPresent
  tags:
# For OMEC - Those images are stable image for RiaB
# latest Aether helm chart commit ID: 3d1e936e87b4ddae784a33f036f87899e9d00b95
#    init: docker.io/omecproject/pod-init:1.0.0
#    depCheck: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
    hssdb: docker.io/onosproject/riab-hssdb:v1.0.0
    hss: docker.io/onosproject/riab-hss:v1.0.0
    mme: docker.io/onosproject/riab-nucleus-mme:v1.0.0
    spgwc: docker.io/onosproject/riab-spgw:v1.0.0
    pcrf: docker.io/onosproject/riab-pcrf:v1.0.0
    pcrfdb: docker.io/onosproject/riab-pcrfdb:v1.0.0
    bess: docker.io/onosproject/riab-bess-upf:v1.0.0
    pfcpiface: docker.io/onosproject/riab-pfcpiface:v1.0.0
# For OAI
    oaicucp: docker.io/onosproject/oai-enb-cu:v0.1.4
    oaidu: docker.io/onosproject/oai-enb-du:v0.1.4
    oaiue: docker.io/onosproject/oai-ue:v0.1.4

# For SD-RAN Umbrella chart:
# ONOS-KPIMON xAPP is imported in the RiaB by default
import:
  onos-kpimon-v1:
    enabled: false
  onos-kpimon-v2:
    enabled: true
  onos-pci:
    enabled: false
# Other ONOS-RIC micro-services
#   onos-topo:
#     enabled: true
#   onos-e2t:
#     enabled: true
#   onos-e2sub:
#     enabled: true
#   onos-o1t:
#     enabled: false
#   onos-config:
#     enabled: true
#   onos-sdran-cli:
#     enabled: true
# ran-simulator chart is automatically imported when pushing ransim option
#   ran-simulator:
#     enabled: false
#   onos-gui:
#     enabled: false
#   nem-monitoring:
#     enabled: false
# fb-ah-xapp, fb-ah-gui, and ah-eson-test-server are automatically imported when pushing fbc-pci option
#   fb-ah-xapp:
#     enabled: false
#   fb-ah-gui:
#     enabled: false
#   ah-eson-test-server:
#     enabled: false