# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

Vagrant.configure(2) do |config|
    config.vm.define "ran" do |ran|
        ran.vm.box = "generic/ubuntu1804"
        ran.vm.disk :disk, size: "30GB", primary: true
        ran.vm.hostname = "ran"
        ran.vm.network :public_network, :dev => "br0", :ovs => true, :mode => "bridge", :type => "bridge"
        ran.vm.provider "libvirt" do |v|
            v.cpus = 4
            v.memory = 8192
        end

        ran.vm.provision "shell", inline: <<-SHELL
            sudo apt update -y
            sudo apt install -y software-properties-common python3-pip jq httpie ipvsadm ethtool
            sudo bash -c 'echo net.ipv4.ip_forward = 1 >> /etc/sysctl.conf'
        SHELL

        ran.vm.provision "shell", run: 'always', inline: <<-SHELL
            sudo ifconfig eth1 192.168.11.10/24 up || true
            sudo ip addr add 192.168.13.21/24 dev eth1 || true
            sudo route add -net 192.168.10.0/24 dev eth1 || true
            sudo route add -net 192.168.11.0/24 dev eth1 || true
        SHELL
    end
end