# Copyright 2020-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0

# cassandra values
cassandra:
  config:
    cluster_size: 1
    seed_size: 1

resources:
  enabled: false

config:
  spgwc:
    multiUpfs: true
    pfcp: true
    jsonCfgFiles:
      subscriber_mapping.json:
        subscriber-selection-rules:
          - priority: 5
            keys:
              serving-plmn:
                mcc: 208
                mnc: 10
                tac: 1
              imsi-range:
                from: 200000000000000
                to: 299999999999999
            selected-apn-profile: apn-profile1
            selected-qos-profile: qos-profile1
            selected-access-profile:
              - access-all
            selected-user-plane-profile: user-plane1
          - priority: 10
            keys:
              match-all: true
            selected-apn-profile: apn-profile1
            selected-qos-profile: qos-profile1
            selected-access-profile:
              - access-all
            selected-user-plane-profile: user-plane1
        apn-profiles:
          apn-profile1:
            apn-name: internet
            usage: 1
            network: lbo
            gx_enabled: true
            dns_primary: 8.8.8.4
            dns_secondary: 8.8.8.8
            mtu: 1460
    ueIpPool:
      ip: 172.250.0.0 # if we use RiaB, Makefile script will override this value with the value defined in Makefile script.
  upf:
    privileged: true
    enb:
      subnet: 192.168.251.0/24
    access:
      gateway: 192.168.252.1
      ip: 192.168.252.3/24
    core:
      gateway: 192.168.250.1
      ip: 192.168.250.3/24
    name: "oaisim"
    sriov:
      enabled: false
    hugepage:
      enabled: false
    cniPlugin: simpleovs
    ipam: static
    cfgFiles:
      upf.json:
        mode: af_packet
  mme:
    cfgFiles:
      config.json:
        mme:
          mcc:
            dig1: 2
            dig2: 0
            dig3: 8
          mnc:
            dig1: 0
            dig2: 1
            dig3: -1
          apnlist:
            internet: "spgwc"
          plmnlist:
            plmn1: "mcc=315,mnc=010"
            plmn2: "mcc=208,mnc=01"
  hss:
    bootstrap:
      users:
        - apn: "internet"
          key: "465b5ce8b199b49faa5f0a2ee238a6bc"
          opc: "d4416644f6154936193433dd20a0ace0"
          sqn: 96
          imsiStart: "208014567891201"
          msisdnStart: "1122334455"
          count: 10
      mmes:
        - id: 1
          mme_identity: mme.riab.svc.cluster.local
          mme_realm: riab.svc.cluster.local
          isdn: "19136246000"
          unreachability: 1
  oai-enb-cu:
    networks:
      f1:
        interface: eno1 # if we use RiaB, Makefile script will automatically apply appropriate interface name
        address: 10.128.100.100 #if we use RiaB, Makefile script will automatically apply appropriate IP address
      s1mme:
        interface: eno1 # if we use RiaB, Makefile script will automatically apply appropriate interface name
      s1u:
        interface: enb
  oai-enb-du:
    mode: nfapi #or local_L1 for USRP and BasicSim
    networks:
      f1:
        interface: eno1 #if we use RiaB, Makefile script will automatically apply appropriate IP address
        address: 10.128.100.100 #if we use RiaB, Makefile script will automatically apply appropriate IP address
      nfapi:
        interface: eno1 #if we use RiaB, Makefile script will automatically apply appropriate IP address
        address: 10.128.100.100 #if we use RiaB, Makefile script will automatically apply appropriate IP address
  oai-ue:
    numDevices: 1 # support up to 3
    networks:
      nfapi:
        interface: eno1 #if we use RiaB, Makefile script will automatically apply appropriate IP address
        address: 10.128.100.100 #if we use RiaB, Makefile script will automatically apply appropriate IP address
  onos-e2t:
    enabled: "yes"
    networks:
      e2:
        address: 127.0.0.1 # if we use RiaB, Makefile script will automatically apply appropriate interface name
        port: 36421

# for the development, we can use the custom images
# For ONOS-RIC
onos-topo:
  image:
    pullPolicy: IfNotPresent
    repository: onosproject/onos-topo
    tag: latest
  logging:
    loggers:
      root:
        level: info
onos-uenib:
  image:
    pullPolicy: IfNotPresent
    repository: onosproject/onos-uenib
    tag: latest
  logging:
    loggers:
      root:
        level: info
onos-config:
  image:
    pullPolicy: IfNotPresent
    repository: onosproject/onos-config
    tag: latest
  logging:
    loggers:
      root:
        level: info
onos-e2t:
  service:
    external:
      enabled: true
    e2:
     nodePort: 36421
  image:
    pullPolicy: IfNotPresent
    repository: onosproject/onos-e2t
    tag: latest
  logging:
    loggers:
      root:
        level: info
onos-cli:
  image:
    pullPolicy: IfNotPresent
    repository: onosproject/onos-cli
    tag: latest
  logging:
    loggers:
      root:
        level: info
ran-simulator:
  image:
    pullPolicy: IfNotPresent
    repository: onosproject/ran-simulator
    tag: latest
  pci:
    modelName: "model"
    metricName: "metrics"
  logging:
    loggers:
      root:
        level: info
onos-kpimon:
  image:
    pullPolicy: IfNotPresent
    repository: onosproject/onos-kpimon
    tag: latest
  logging:
    loggers:
      root:
        level: info
onos-pci:
  image:
    pullPolicy: IfNotPresent
    repository: onosproject/onos-pci
    tag: latest
  logging:
    loggers:
      root:
        level: info
onos-mlb:
  image:
    pullPolicy: IfNotPresent
    repository: onosproject/onos-mlb
    tag: latest
  logging:
    loggers:
      root:
        level: info
  config:
    mlb:
      e2tEndpoint: "onos-e2t:5150"
      thresholds:
        overload: 100
        target: 0
      config_json:
        controller:
          interval: 10
onos-mho:
  image:
    pullPolicy: IfNotPresent
    repository: onosproject/onos-mho
    tag: latest
  logging:
    loggers:
      root:
        level: info
  config:
    mho:
        e2tEndpoint: "onos-e2t:5150"
        config_json:
          reportingPeriod: 1000
          periodic: true
          uponRcvMeasReport: true
          uponChangeRrcStatus: true
          A3OffsetRange: 0
          HysteresisRange: 0
          CellIndividualOffset: 0
          FrequencyOffset: 0
          TimeToTrigger: 0
onos-rsm:
  image:
    repository: onosproject/onos-rsm
    tag: latest
    pullPolicy: IfNotPresent
fb-ah-xapp:
  image:
    repository: onosproject/fb-ah-xapp
    tag: 0.0.4
    pullPolicy: IfNotPresent
fb-kpimon-xapp:
  image:
    repository: onosproject/fb-kpimon-xapp
    tag: 0.0.2
    pullPolicy: IfNotPresent
fb-ah-gui:
  image:
    repository: onosproject/fb-ah-gui
    tag: 0.0.2
    pullPolicy: IfNotPresent
ah-eson-test-server:
  image:
    repository: onosproject/ah-eson-test-server
    tag: 0.0.2
    pullPolicy: IfNotPresent

# For OMEC & OAI
images:
  pullPolicy: IfNotPresent
  tags:
# For OMEC - Those images are stable image for RiaB
# latest Aether helm chart commit ID: 3d1e936e87b4ddae784a33f036f87899e9d00b95
#    init: docker.io/omecproject/pod-init:1.0.0
#    depCheck: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
    hssdb: docker.io/onosproject/riab-hssdb:master-9de5dba
    hss: docker.io/onosproject/riab-hss:master-9de5dba
    mme: docker.io/onosproject/riab-nucleus-mme:master-9e2bf16
    spgwc: docker.io/onosproject/riab-spgw:master-d8b0987-onfvm-1
    pcrf: docker.io/onosproject/riab-pcrf:pcrf-b29af70
    pcrfdb: docker.io/onosproject/riab-pcrfdb:pcrf-b29af70
    bess: docker.io/onosproject/riab-bess-upf:master-635b4d4-onfvm-1
    pfcpiface: docker.io/onosproject/riab-pfcpiface:master-635b4d4-onfvm-1
# For OAI
    oaicucp: docker.io/onosproject/oai-enb-cu:latest
    oaidu: docker.io/onosproject/oai-enb-du:latest
    oaiue: docker.io/onosproject/oai-ue:latest

# For SD-RAN Umbrella chart:
# ONOS-KPIMON xAPP and ONOS-UENIB are imported in the RiaB by default
# ONOS-PCI xApp is imported in the RiaB when using OPT=ransim and OPT=mlb
# ONOS-MLB xApp is imported in the RiaB when using OPT=mlb
# ONOS-MHO xApp is imported in the RiaB when using OPT=mho
import:
  onos-uenib:
    enabled: true
  onos-kpimon:
    enabled: true
  onos-pci:
    enabled: false
  onos-mlb:
    enabled: false
  onos-mho:
    enabled: false
# Other ONOS-RIC micro-services
#   onos-topo:
#     enabled: true
#   onos-e2t:
#     enabled: true
#   onos-e2sub:
#     enabled: true
#   onos-o1t:
#     enabled: false
#   onos-config:
#     enabled: true
#   onos-sdran-cli:
#     enabled: true
# ran-simulator chart is automatically imported when pushing ransim option
#   ran-simulator:
#     enabled: false
#   onos-gui:
#     enabled: false
#   nem-monitoring:
#     enabled: false
# fb-ah-xapp, fb-ah-gui, and ah-eson-test-server are automatically imported when pushing fbc-pci option
#   fb-ah-xapp:
#     enabled: false
#   fb-ah-gui:
#     enabled: false
#   ah-eson-test-server:
#     enabled: false
# Monitoring/Logging
#   fluent-bit:
#     enabled: true
#   opendistro-es:
#     enabled: true
#   prometheus-stack:
#     enabled: true
